### ISSUE TITLE
Pluralsight Demo

### ISSUE THREAD

**Issue by mdlister** [Daniel-Krzyczkowski/Pluralsight#3]
Just following your Azure Devops Engineer training on Route System Feedback to Development Teams. 

I've cloned the Repo and following steps in module two we have successfully rebuilt the code. When I run the API in Visual Studio 2019 I get HTTP Error 500.31 

HTTP Error 500.31 - ANCM Failed to Find Native Dependencies
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.
Specific error detected by ANCM:
It was not possible to find any compatible framework version The framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found. - The following frameworks were found: 2.1.19 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] 3.1.5 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] You can resolve the problem by installing the specified framework and/or SDK. The specified framework can be found at: - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64

**Comment by Daniel-Krzyczkowski** [comment]
Hi, thank you so much for reporting this issue.
This problem is related to the .NET Core SDK and Runtime version. In the API and Web App projects there is .NET Core 2.2 used so if you do not have it installed on the local machine, problem can occur.
In the nearest future I will try to update this sample and migrate to .NET Core 3.1.

**Comment by Daniel-Krzyczkowski** [comment]
I migrated Web API and Web App projects to the .NET Core 3.1. Now everything should be fine. Please pull the latest source code from the repository. If there will be any issues, please let me know. Thank you.

**Comment by Daniel-Krzyczkowski** [comment]
Closing the issue.
